(1)updated in django_db_logger
file path : env/lib/python3.6/site-packages/django_db_logger/models.py
Changes:
-comment line no 3
#from django.utils.encoding import python_2_unicode_compatible
-comments line no 16
#@python_2_unicode_compatible
-restart server
--------------------------------------------------------------------------------
